ktor {
    deployment {
        port = 8080
        port = ${?SERVER_PORT}
        host = "0.0.0.0"
        host = ${?SERVER_HOST}
    }
    application {
        modules = [ org.kotlinlang.mcp.ApplicationKt.module ]
    }
}

algolia {
    appId = ${ALGOLIA_APP_ID}
    apiKey = ${ALGOLIA_API_KEY}
    indexName = ${ALGOLIA_INDEX_NAME}
}
